name = "Slime Skies"
author = "copygirl"
version = "0.5.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af3ba3f5122424e0d805fe0b444f596a68f26f489eff1c48080f5f9c18685fb8"

[versions]
forge = "36.2.4"
minecraft = "1.16.5"
