
["Balance Options"]
	#Minimum temperature of fluid at which the Ceramic Bucket breaks when emptied. (-1 means that bucket never breaks caused by high fluid temperature)
	#Range: -1 ~ 10000
	ceramicBucketBreakTemperature = 1000
	#Whether or not obtaining fish with a Ceramic Bucket should be enabled.
	fishObtainingEnabled = true
	#Whether or not milking entities with a Ceramic Bucket should be enabled.
	milkingEnabled = true
	#Whether or not Infinity enchantment for Ceramic Buckets filled with multiplying sources like water should be enabled.
	infinityEnchantmentEnabled = true
