name = "Forgery"
filename = "forgery-1.16-1.4.0_01.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3508/770/forgery-1.16-1.4.0_01.jar"
hash-format = "murmur2"
hash = "3928431122"

[update]
[update.curseforge]
file-id = 3508770
project-id = 434087
